version: '3.6'

services:
  backend-scrapper:
    container_name: backend-scrapper
    build: ./web-scrapper
    depends_on:
      - db
    volumes:
      - data:/var/lib/pgsql/data
    ports:
      - "8000:8000"

  db:
    image: postgres:12.16-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luxonis

  frontend-react:
    container_name: frontend-react
    build: ./react-frontend
    depends_on:
      - backend-scrapper
      - db
    ports:
      - "8080:80"

volumes:
  data:
